import json, sys

data = {
    'band_gap.json': {'indirect_gap': 3.764, 'direct_gap': 3.799},
    'phonon_modes.json': {'phonon_modes': [
        {'TO_frequency': 54.2, 'LO_frequency': 54.6, 'symmetry': 'B1u', 'mode_type': 'IR', 'Z_star': 0.11, 'dielectric_intensity': 0.02},
        {'TO_frequency': 108.4, 'LO_frequency': 112.3, 'symmetry': 'B3u', 'mode_type': 'IR', 'Z_star': 2.35, 'dielectric_intensity': 1.69},
        {'TO_frequency': 140.5, 'LO_frequency': 145.0, 'symmetry': 'B2u', 'mode_type': 'IR', 'Z_star': 3.19, 'dielectric_intensity': 1.86},
        {'TO_frequency': 185.7, 'LO_frequency': 190.0, 'symmetry': 'B2u', 'mode_type': 'IR', 'Z_star': 0.87, 'dielectric_intensity': 0.08},
        {'TO_frequency': 203.6, 'LO_frequency': 204.7, 'symmetry': 'B1u', 'mode_type': 'IR', 'Z_star': 6.21, 'dielectric_intensity': 2.51},
        {'TO_frequency': 204.7, 'LO_frequency': 208.5, 'symmetry': 'B3u', 'mode_type': 'IR', 'Z_star': 4.88, 'dielectric_intensity': 1.54},
        {'TO_frequency': 229.8, 'LO_frequency': 236.2, 'symmetry': 'B3u', 'mode_type': 'IR', 'Z_star': 5.58, 'dielectric_intensity': 4.08},
        {'TO_frequency': 236.3, 'LO_frequency': 259.3, 'symmetry': 'B2u', 'mode_type': 'IR', 'Z_star': 8.43, 'dielectric_intensity': 11.27},
        {'TO_frequency': 269.7, 'LO_frequency': 286.6, 'symmetry': 'B1u', 'mode_type': 'IR', 'Z_star': 6.52, 'dielectric_intensity': 5.56},
        {'TO_frequency': 297.8, 'LO_frequency': 307.1, 'symmetry': 'B1u', 'mode_type': 'IR', 'Z_star': 2.97, 'dielectric_intensity': 0.41},
        {'TO_frequency': 311.2, 'LO_frequency': 313.5, 'symmetry': 'B2u', 'mode_type': 'IR', 'Z_star': 1.32, 'dielectric_intensity': 0.05},
        {'TO_frequency': 314.8, 'LO_frequency': 316.9, 'symmetry': 'B3u', 'mode_type': 'IR', 'Z_star': 3.53, 'dielectric_intensity': 1.40},
        {'TO_frequency': 338.6, 'LO_frequency': 342.8, 'symmetry': 'B1u', 'mode_type': 'IR', 'Z_star': 3.34, 'dielectric_intensity': 0.30},
        {'TO_frequency': 352.2, 'LO_frequency': 356.4, 'symmetry': 'B3u', 'mode_type': 'IR', 'Z_star': 9.53, 'dielectric_intensity': 3.17},
        {'TO_frequency': 371.6, 'LO_frequency': 373.2, 'symmetry': 'B1u', 'mode_type': 'IR', 'Z_star': 4.03, 'dielectric_intensity': 1.15},
        {'TO_frequency': 373.3, 'LO_frequency': 385.9, 'symmetry': 'B3u', 'mode_type': 'IR', 'Z_star': 8.65, 'dielectric_intensity': 2.61},
        {'TO_frequency': 416.3, 'LO_frequency': 420.1, 'symmetry': 'B2u', 'mode_type': 'IR', 'Z_star': 7.49, 'dielectric_intensity': 3.64},
        {'TO_frequency': 449.8, 'LO_frequency': 455.5, 'symmetry': 'B1u', 'mode_type': 'IR', 'Z_star': 9.03, 'dielectric_intensity': 4.44},
        {'TO_frequency': 455.6, 'LO_frequency': 457.3, 'symmetry': 'B2u', 'mode_type': 'IR', 'Z_star': 4.25, 'dielectric_intensity': 1.02},
        {'TO_frequency': 457.4, 'LO_frequency': 521.6, 'symmetry': 'B3u', 'mode_type': 'IR', 'Z_star': 5.77, 'dielectric_intensity': 1.81},
        {'TO_frequency': 620.9, 'LO_frequency': 631.5, 'symmetry': 'B2u', 'mode_type': 'IR', 'Z_star': 3.16, 'dielectric_intensity': 0.29},
        {'TO_frequency': 636.7, 'LO_frequency': 648.8, 'symmetry': 'B1u', 'mode_type': 'IR', 'Z_star': 2.18, 'dielectric_intensity': 0.14},
        {'TO_frequency': 648.9, 'LO_frequency': 649.2, 'symmetry': 'B3u', 'mode_type': 'IR', 'Z_star': 0.37, 'dielectric_intensity': 0.004},
        {'TO_frequency': 666.4, 'LO_frequency': 667.4, 'symmetry': 'B3u', 'mode_type': 'IR', 'Z_star': 3.52, 'dielectric_intensity': 0.30},
        {'TO_frequency': 667.5, 'LO_frequency': 671.4, 'symmetry': 'B1u', 'mode_type': 'IR', 'Z_star': 3.17, 'dielectric_intensity': 0.24},
        {'TO_frequency': 134.9, 'LO_frequency': 134.9, 'symmetry': 'Ag', 'mode_type': 'Raman', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 160.8, 'LO_frequency': 160.8, 'symmetry': 'B2g', 'mode_type': 'Raman', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 181.3, 'LO_frequency': 181.3, 'symmetry': 'B1g', 'mode_type': 'Raman', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 191.8, 'LO_frequency': 191.8, 'symmetry': 'B3g', 'mode_type': 'Raman', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 201.9, 'LO_frequency': 201.9, 'symmetry': 'B2g', 'mode_type': 'Raman', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 214.1, 'LO_frequency': 214.1, 'symmetry': 'Ag', 'mode_type': 'Raman', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 261.1, 'LO_frequency': 261.1, 'symmetry': 'B1g', 'mode_type': 'Raman', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 286.6, 'LO_frequency': 286.6, 'symmetry': 'Ag', 'mode_type': 'Raman', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 313.5, 'LO_frequency': 313.5, 'symmetry': 'B2g', 'mode_type': 'Raman', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 333.2, 'LO_frequency': 333.2, 'symmetry': 'B3g', 'mode_type': 'Raman', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 356.4, 'LO_frequency': 356.4, 'symmetry': 'Ag', 'mode_type': 'Raman', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 413.3, 'LO_frequency': 413.3, 'symmetry': 'B2g', 'mode_type': 'Raman', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 521.6, 'LO_frequency': 521.6, 'symmetry': 'B3g', 'mode_type': 'Raman', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 526.4, 'LO_frequency': 526.4, 'symmetry': 'B1g', 'mode_type': 'Raman', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 534.2, 'LO_frequency': 534.2, 'symmetry': 'Ag', 'mode_type': 'Raman', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 593.0, 'LO_frequency': 593.0, 'symmetry': 'B1g', 'mode_type': 'Raman', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 631.5, 'LO_frequency': 631.5, 'symmetry': 'Ag', 'mode_type': 'Raman', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 649.2, 'LO_frequency': 649.2, 'symmetry': 'B3g', 'mode_type': 'Raman', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 650.4, 'LO_frequency': 650.4, 'symmetry': 'B2g', 'mode_type': 'Raman', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 671.5, 'LO_frequency': 671.5, 'symmetry': 'Ag', 'mode_type': 'Raman', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 672.3, 'LO_frequency': 672.3, 'symmetry': 'B2g', 'mode_type': 'Raman', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 709.1, 'LO_frequency': 709.1, 'symmetry': 'B1g', 'mode_type': 'Raman', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 751.2, 'LO_frequency': 751.2, 'symmetry': 'B2g', 'mode_type': 'Raman', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 760.1, 'LO_frequency': 760.1, 'symmetry': 'B3g', 'mode_type': 'Raman', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 81.6, 'LO_frequency': 81.6, 'symmetry': 'Au', 'mode_type': 'Silent', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 148.7, 'LO_frequency': 148.7, 'symmetry': 'Au', 'mode_type': 'Silent', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 161.1, 'LO_frequency': 161.1, 'symmetry': 'Au', 'mode_type': 'Silent', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 259.3, 'LO_frequency': 259.3, 'symmetry': 'Au', 'mode_type': 'Silent', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 296.7, 'LO_frequency': 296.7, 'symmetry': 'Au', 'mode_type': 'Silent', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 420.1, 'LO_frequency': 420.1, 'symmetry': 'Au', 'mode_type': 'Silent', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 434.3, 'LO_frequency': 434.3, 'symmetry': 'Au', 'mode_type': 'Silent', 'Z_star': None, 'dielectric_intensity': None},
        {'TO_frequency': 636.4, 'LO_frequency': 636.4, 'symmetry': 'Au', 'mode_type': 'Silent', 'Z_star': None, 'dielectric_intensity': None}
    ]},
    'dielectric_tensor.json': {
        'epsilon_infinity': {'xx': 5.12, 'yy': 4.93, 'zz': 4.83, 'average': 4.96},
        'epsilon_ionic': {'xx': 14.77, 'yy': 16.60, 'zz': 18.21, 'average': 16.53},
        'epsilon_0': {'xx': 19.89, 'yy': 21.53, 'zz': 23.04, 'average': 21.49}
    }
}

name = sys.argv[1]
with open('/app/outputs/' + name, 'w') as f:
    json.dump(data[name], f, indent=2)
