schema_version = "1.3"

[task]
name = "flowforge/paper-812283423065374721"
description = "Estimation of Surface Free Energies and Equilibrium Vapor Pressure of Quaterthiophene for Nucleation Analysis"

[agent]
timeout_sec = 18000

[verifier]
timeout_sec = 11400

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
