schema_version = "1.3"

[task]
name = "flowforge/paper-812597389423542273"
description = "Phonon, Electronic, and Thermoelectric Properties of TiMoCO2 MXene Alloy"

[agent]
timeout_sec = 400000

[verifier]
timeout_sec = 20000

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
