schema_version = "1.3"

[task]
name = "flowforge/paper-813328397135511553"
description = "DFT study of structure, mechanics, hardness and thermal properties of orthorhombic A2N2O compounds"

[agent]
timeout_sec = 300000

[verifier]
timeout_sec = 11400

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
