schema_version = "1.3"

[task]
name = "flowforge/paper-812123561538879488"
description = "Corrected Adsorption Energies of Xylene Isomers on H-MOR Zeolite"

[agent]
timeout_sec = 172800

[verifier]
timeout_sec = 11400

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
