schema_version = "1.3"

[task]
name = "flowforge/paper-811973975843274754"
description = "Surface‑Enhanced Raman Scattering (SERS) Enhancement Factor Calculation for Langmuir‑Blodgett Film on Nanostructured Metal Surface"

[agent]
timeout_sec = 86400

[verifier]
timeout_sec = 11400

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
