schema_version = "1.3"

[task]
name = "flowforge/paper-811783493397774341"
description = "Calculation of Lattice Energies and Densities for α- and β-SrNCN Polymorphs"

[agent]
timeout_sec = 21600

[verifier]
timeout_sec = 14400

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
