schema_version = "1.3"

[task]
name = "flowforge/paper-813020831692095490"
description = "DFT-MD and Metadynamics of a Palladium-Chromium Hemichelate Complex"

[agent]
timeout_sec = 600000

[verifier]
timeout_sec = 11400

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
