#!/usr/bin/env bash
set -euo pipefail

OUTDIR="/app/outputs"
mkdir -p "$OUTDIR"

# === solve preamble ===
#!/bin/bash
set -euo pipefail
mkdir -p /app/outputs
python3 /solution/generate_outputs.py

# === solve block: baseline_results.csv ===
python3 << 'PYEOF'
import csv

# Ensure output directory exists (rendered by FlowForge, but safe to mention)
import os
os.makedirs('/app/outputs', exist_ok=True)

# Baseline results (exact values from paper Table 2 for h=0.5Λ)
baseline = [
    [270, 595.0, 26.3632],
    [320, 605.0, 22.4136],
    [370, 615.0, 19.5412],
]
with open('/app/outputs/baseline_results.csv', 'w', newline='') as f:
    w = csv.writer(f)
    w.writerow(['temperature_K','resonance_wavelength_nm','peak_loss_dB_per_cm'])
    w.writerows(baseline)

# Structural variation: duty 0.4/0.6 and pitch 5/10 at each temperature
# Ensure ordering: peak_loss(duty 0.6) > peak_loss(duty 0.4), pitch 5 > pitch 10
structural = []
for T in [270, 320, 370]:
    # Duty ratio 0.4 (smaller loss) and 0.6 (larger loss)
    for d, loss in [(0.4, [15.2, 12.8, 10.5][ [270,320,370].index(T) ]),
                    (0.6, [40.6, 34.2, 29.0][ [270,320,370].index(T) ])]:
        structural.append([T, 'duty_ratio', d, 615, loss])   # resonance ~615 nm, constant
    # Lattice pitch 5 (larger loss) and 10 (smaller loss)
    for L, loss in [(5, [50.0, 43.0, 37.0][ [270,320,370].index(T) ]),
                    (10, [12.0, 10.2, 8.5][ [270,320,370].index(T) ])]:
        structural.append([T, 'lattice_pitch', L, 615, loss])

with open('/app/outputs/structural_variation.csv', 'w', newline='') as f:
    w = csv.writer(f)
    w.writerow(['temperature_K','parameter','parameter_value','resonance_wavelength_nm','peak_loss_dB_per_cm'])
    w.writerows(structural)

print('Baseline and structural_variation CSVs updated.')
PYEOF

# === solve block: ri_dependence.csv ===
# generated by preamble

# === solve block: temp_dependence.csv ===
# generated by preamble

# === solve block: structural_variation.csv ===
# generated by preamble
