schema_version = "1.3"

[task]
name = "flowforge/paper-812085469708812290"
description = "Reproducing Dissociation Energies and Hydrogen-Bond Critical Point Densities of BASE-HF Complexes"

[agent]
timeout_sec = 72000

[verifier]
timeout_sec = 11400

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
