schema_version = "1.3"

[task]
name = "flowforge/paper-813152750756954113"
description = "Zeolite Screening for Adsorption and Diffusion of SO2, CO2, and CO via GCMC Simulations"

[agent]
timeout_sec = 72000

[verifier]
timeout_sec = 12000

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
