#!/usr/bin/env bash
set -euo pipefail

OUTDIR="/app/outputs"
mkdir -p "$OUTDIR"

# === solve preamble ===
#!/bin/bash
set -euo pipefail
mkdir -p /app/outputs
python3 -m pip install -q --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple numpy
python3 /solution/generate_outputs.py

# === solve block: band_gaps.csv ===
{
  echo "x,band_gap_unshifted"
  for x in 0.0 0.1 0.3 0.5 0.9 1.0; do
    unshifted=$(awk -v x="$x" 'BEGIN{ printf "%.6f", 1.6367 + 0.2732 * exp(-6.2*x) }')
    echo "${x},${unshifted}"
  done
} > "$OUTDIR/band_gaps.csv"

# === solve block: epsilon2.csv ===
echo "epsilon2.csv generated by preamble"

# === solve block: epsilon1.csv ===
echo "epsilon1.csv generated by preamble"
