schema_version = "1.3"

[task]
name = "flowforge/paper-811914235536736258"
description = "LSFD Peptide β-Hairpin Folding via Molecular Dynamics"

[agent]
timeout_sec = 2400000

[verifier]
timeout_sec = 11400

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
