schema_version = "1.3"

[task]
name = "flowforge/paper-812347177819963393"
description = "DFT Formation Energy and Stability of Fe-K Substitutional Alloy under High Pressure"

[agent]
timeout_sec = 720000

[verifier]
timeout_sec = 11400

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
