schema_version = "1.3"

[task]
name = "flowforge/paper-813126579478593536"
description = "DFT Simulation of Pentanoic Acid Adsorption on α‑Al₂O₃ Surfaces"

[agent]
timeout_sec = 691200

[verifier]
timeout_sec = 11400

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
