schema_version = "1.3"

[task]
name = "flowforge/paper-1201875355921547273"
description = "Electronic Thermoelectric Figure of Merit of SnSe-based Hybrids and Nanostructured CsPbI3"

[agent]
timeout_sec = 86400

[verifier]
timeout_sec = 11400

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
