schema_version = "1.3"

[task]
name = "flowforge/paper-320824240603398144"
description = "DFT+U Band Gaps and Sodium Extraction Potentials of NaMFe(MoO₄)₃ Double Molybdates"

[agent]
timeout_sec = 766800

[verifier]
timeout_sec = 11400

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
