schema_version = "1.3"

[task]
name = "flowforge/paper-867752528257745543"
description = "Dislocation Core Structure and Energy from Deep Potential Simulations in FCC Copper"

[agent]
timeout_sec = 43200

[verifier]
timeout_sec = 12000

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
