# Helper script for the hidden oracle – writes the paper's Tables 1 and 2 as CSV files.
import csv
import sys

D2H_ROWS = [
    # space_group_number, symbol, allowed_permutations, defined_axes, invariant_sites,
    # abc, bca, cab, bač, čba, ačb
    {
        "space_group_number": 47,
        "symbol": "P2/m2/m2/m",
        "allowed_permutations": "Any",
        "defined_axes": "---",
        "invariant_sites": "a\nh\n\\alpha",
        "abc": "b\nd\ni\nj\nl\nu\nv",
        "bca": "c\ng\nq\nr\nt\ny\nz",
        "cab": "e\nf\nm\no\np\nw\nx",
        "bač": "e\ng\nm\nn\np\nw\nx",
        "čba": "c\nd\nq\ns\nt\ny\nz",
        "ačb": "b\nf\ni\nk\nl\nu\nv",
    },
    {
        "space_group_number": 48,
        "symbol": "P2/n2/n2/n",
        "allowed_permutations": "Any",
        "defined_axes": "---",
        "invariant_sites": "a\ne\nf\nm",
        "abc": "b\ng\nh",
        "bca": "c\nk\nl",
        "cab": "d\ni\nj",
        "bač": "d\ni\nj",
        "čba": "c\nk\nl",
        "ačb": "b\ng\nh",
    },
    {
        "space_group_number": 49,
        "symbol": "P2/c2/c2/m",
        "allowed_permutations": "ba\\bar c",
        "defined_axes": "c_0\\perp m",
        "invariant_sites": "a\nb\ne\nh\nq\nn\nm\nr",
        "abc": "c\nf\ni\nj\no",
        "bca": "",
        "cab": "",
        "bač": "d\ng\nk\nl\np",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 50,
        "symbol": "P2/b2/a2/n",
        "allowed_permutations": "ba\\bar c",
        "defined_axes": "c_0\\perp n",
        "invariant_sites": "a\nb\nc\nd\ne\nf\nk\nl\nm",
        "abc": "g\nh",
        "bca": "",
        "cab": "",
        "bač": "i\nj",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 51,
        "symbol": "P2_1/m2/m2/a",
        "allowed_permutations": "---",
        "defined_axes": "a_0\\parallel 2_1 c_0\\perp a",
        "invariant_sites": "",
        "abc": "",
        "bca": "",
        "cab": "",
        "bač": "",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 52,
        "symbol": "P2/n2_1/n2/a",
        "allowed_permutations": "---",
        "defined_axes": "b_0\\parallel 2_1 c_0\\perp a",
        "invariant_sites": "",
        "abc": "",
        "bca": "",
        "cab": "",
        "bač": "",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 53,
        "symbol": "P2/m2/n2_1/a",
        "allowed_permutations": "---",
        "defined_axes": "a_0\\perp m b_0\\perp n c_0\\parallel 2_1",
        "invariant_sites": "",
        "abc": "",
        "bca": "",
        "cab": "",
        "bač": "",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 54,
        "symbol": "P2_1/c2/c2/a",
        "allowed_permutations": "---",
        "defined_axes": "a_0\\parallel 2_1 c_0\\perp a",
        "invariant_sites": "",
        "abc": "",
        "bca": "",
        "cab": "",
        "bač": "",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 55,
        "symbol": "P2_1/b2_1/a2/m",
        "allowed_permutations": "ba\\bar c",
        "defined_axes": "c_0\\perp m",
        "invariant_sites": "All sites",
        "abc": "",
        "bca": "",
        "cab": "",
        "bač": "",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 56,
        "symbol": "P2_1/c2_1/c2/n",
        "allowed_permutations": "ba\\bar c",
        "defined_axes": "c_0\\perp n",
        "invariant_sites": "All sites",
        "abc": "",
        "bca": "",
        "cab": "",
        "bač": "",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 57,
        "symbol": "P2/b2_1/c2_1/m",
        "allowed_permutations": "---",
        "defined_axes": "a_0\\parallel 2 b_0\\parallel 2_1 c_0\\perp m",
        "invariant_sites": "",
        "abc": "",
        "bca": "",
        "cab": "",
        "bač": "",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 58,
        "symbol": "P2_1/n2_1/n2/m",
        "allowed_permutations": "ba\\bar c",
        "defined_axes": "c_0\\perp m",
        "invariant_sites": "a\nb\nc\nd",
        "abc": "",
        "bca": "",
        "cab": "",
        "bač": "",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 59,
        "symbol": "P2_1/m2_1/m2/n",
        "allowed_permutations": "ba\\bar c",
        "defined_axes": "c_0\\perp n c_0\\parallel 2",
        "invariant_sites": "a\nb\nc\nd\ng",
        "abc": "f",
        "bca": "",
        "cab": "",
        "bač": "e",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 60,
        "symbol": "P2_1/b2/c2_1/n",
        "allowed_permutations": "---",
        "defined_axes": "b_0\\parallel 2 c_0\\perp n",
        "invariant_sites": "",
        "abc": "",
        "bca": "",
        "cab": "",
        "bač": "",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 61,
        "symbol": "P2_1/b2_1/c2_1/a",
        "allowed_permutations": "cyclic",
        "defined_axes": "---",
        "invariant_sites": "a\nb\nc",
        "abc": "",
        "bca": "",
        "cab": "",
        "bač": "",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 62,
        "symbol": "P2_1/n2_1/m2_1/a",
        "allowed_permutations": "---",
        "defined_axes": "a_0\\perp n b_0\\perp m",
        "invariant_sites": "",
        "abc": "",
        "bca": "",
        "cab": "",
        "bač": "",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 63,
        "symbol": "C2/m2/c2_1/m",
        "allowed_permutations": "---",
        "defined_axes": "a_0\\perp m c_0\\parallel 2_1",
        "invariant_sites": "",
        "abc": "",
        "bca": "",
        "cab": "",
        "bač": "",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 64,
        "symbol": "C2/m2/c2_1/a",
        "allowed_permutations": "---",
        "defined_axes": "a_0\\perp m c_0\\parallel 2_1",
        "invariant_sites": "",
        "abc": "",
        "bca": "",
        "cab": "",
        "bač": "",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 65,
        "symbol": "C2/m2/m2/m",
        "allowed_permutations": "ba\\bar c",
        "defined_axes": "c_0\\perp centered face",
        "invariant_sites": "a\nb\nc\nd\ne\nf\nk\nm\np\nq\nr",
        "abc": "g\nh\no\ng",
        "bca": "",
        "cab": "",
        "bač": "i\nj\nn\nh",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 66,
        "symbol": "C2/c2/c2/m",
        "allowed_permutations": "ba\\bar c",
        "defined_axes": "c_0\\perp m",
        "invariant_sites": "a\nb\nc\nd\ne\nf\ni\nj\nk\nl\nm",
        "abc": "",
        "bca": "",
        "cab": "",
        "bač": "",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 67,
        "symbol": "C2/m2/m2/a",
        "allowed_permutations": "---",
        "defined_axes": "c_0\\perp a a_0\\parallel glide direction",
        "invariant_sites": "",
        "abc": "",
        "bca": "",
        "cab": "",
        "bač": "",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 68,
        "symbol": "C2/c2/c2/a",
        "allowed_permutations": "---",
        "defined_axes": "c_0\\perp a a_0\\parallel glide direction",
        "invariant_sites": "",
        "abc": "",
        "bca": "",
        "cab": "",
        "bač": "",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 69,
        "symbol": "F2/m2/m2/m",
        "allowed_permutations": "Any",
        "defined_axes": "---",
        "invariant_sites": "a\nb\nf\np",
        "abc": "c\ng\nj\nm\ne",
        "bca": "e\ni\nk\no\ng",
        "cab": "d\nh\nl\nn\nf",
        "bač": "d\nh\nj\nn\nf",
        "čba": "e\ni\nl\no\ng",
        "ačb": "c\ng\nk\nm\ne",
    },
    {
        "space_group_number": 70,
        "symbol": "F2/d2/d2/d",
        "allowed_permutations": "Any",
        "defined_axes": "---",
        "invariant_sites": "a\nb\nc\nd\nh",
        "abc": "",
        "bca": "",
        "cab": "",
        "bač": "",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 71,
        "symbol": "I2/m2/m2/m",
        "allowed_permutations": "Any",
        "defined_axes": "---",
        "invariant_sites": "a\no",
        "abc": "b\ne\nf\nl",
        "bca": "c\ni\nj\nn",
        "cab": "d\ng\nh\nm",
        "bač": "d\ng\nh\nm",
        "čba": "c\ni\nj\nn",
        "ačb": "b\ne\nf\nl",
    },
    {
        "space_group_number": 72,
        "symbol": "I2/b2/a2/m",
        "allowed_permutations": "ba\\bar c",
        "defined_axes": "c_0\\perp m",
        "invariant_sites": "a\nb\nc\nd\ne\nh\ni\nj\nk",
        "abc": "f",
        "bca": "",
        "cab": "",
        "bač": "g",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 73,
        "symbol": "I2/b2/c2/a",
        "allowed_permutations": "cyclic",
        "defined_axes": "---",
        "invariant_sites": "a\nb\nf",
        "abc": "c",
        "bca": "e",
        "cab": "d",
        "bač": "",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 74,
        "symbol": "I2/m2/m2/a",
        "allowed_permutations": "---",
        "defined_axes": "c_0\\perp a a_0\\parallel glide direction",
        "invariant_sites": "",
        "abc": "",
        "bca": "",
        "cab": "",
        "bač": "",
        "čba": "",
        "ačb": "",
    },
]

D2_ROWS = [
    {
        "space_group_number": 16,
        "symbol": "P222",
        "allowed_permutations": "Any",
        "defined_axes": "---",
        "invariant_sites": "a\nh\nu",
        "abc": "b\ne\ni\nj\nl",
        "bca": "d\nf\ng\ns\nt",
        "cab": "c\ng\nm\no\np",
        "bač": "c\ne\nm\nn\np",
        "čba": "d\ng\ng\nr\nt",
        "ačb": "b\nf\ni\nk\nl",
    },
    {
        "space_group_number": 17,
        "symbol": "P222_1",
        "allowed_permutations": "ba\\bar c",
        "defined_axes": "c_0\\parallel 2_1 All \\rightarrow",
        "invariant_sites": "No site coordinates allows a permutation",
        "abc": "",
        "bca": "",
        "cab": "",
        "bač": "",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 18,
        "symbol": "P2_12_12",
        "allowed_permutations": "ba\\bar c",
        "defined_axes": "c_0\\parallel 2",
        "invariant_sites": "a\nb\nc",
        "abc": "",
        "bca": "",
        "cab": "",
        "bač": "",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 19,
        "symbol": "P2_12_12_1",
        "allowed_permutations": "Any",
        "defined_axes": "All \\rightarrow",
        "invariant_sites": "No site coordinates allows a permutation",
        "abc": "",
        "bca": "",
        "cab": "",
        "bač": "",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 20,
        "symbol": "C222_1",
        "allowed_permutations": "ba\\bar c",
        "defined_axes": "c_0\\parallel 2_1 All \\rightarrow",
        "invariant_sites": "No site coordinates allows a permutation",
        "abc": "",
        "bca": "",
        "cab": "",
        "bač": "",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 21,
        "symbol": "C222",
        "allowed_permutations": "ba\\bar c",
        "defined_axes": "c_0\\perp centered face",
        "invariant_sites": "a\nb\nc\nd\ni\nj\nk\nl",
        "abc": "e\nf",
        "bca": "",
        "cab": "",
        "bač": "g\nh",
        "čba": "",
        "ačb": "",
    },
    {
        "space_group_number": 22,
        "symbol": "F222",
        "allowed_permutations": "Any",
        "defined_axes": "---",
        "invariant_sites": "a\nb\nc\nd\nk",
        "abc": "e\nh",
        "bca": "e\ni",
        "cab": "f\nh",
        "bač": "f\nj",
        "čba": "g\nj",
        "ačb": "g\ni",
    },
    {
        "space_group_number": 23,
        "symbol": "I222",
        "allowed_permutations": "Any",
        "defined_axes": "---",
        "invariant_sites": "a\nk",
        "abc": "b\ne\nh",
        "bca": "c\ni\nf",
        "cab": "d\ng\nb",
        "bač": "d\ng\nf",
        "čba": "c\ni\nh",
        "ačb": "b\ne\nj",
    },
    {
        "space_group_number": 24,
        "symbol": "I2_12_12_1",
        "allowed_permutations": "Cyclic",
        "defined_axes": "---",
        "invariant_sites": "d",
        "abc": "a",
        "bca": "c",
        "cab": "",
        "bač": "",
        "čba": "",
        "ačb": "",
    },
]

FIELDNAMES = [
    "space_group_number",
    "symbol",
    "allowed_permutations",
    "defined_axes",
    "invariant_sites",
    "abc",
    "bca",
    "cab",
    "bač",
    "čba",
    "ačb",
]

def main(table_name):
    if table_name == "d2h":
        rows = D2H_ROWS
        outfile = "/app/outputs/d2h_table.csv"
    elif table_name == "d2":
        rows = D2_ROWS
        outfile = "/app/outputs/d2_table.csv"
    else:
        sys.exit("Unknown table")
    with open(outfile, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=FIELDNAMES, quoting=csv.QUOTE_ALL)
        w.writeheader()
        w.writerows(rows)

if __name__ == "__main__":
    main(sys.argv[1])
