schema_version = "1.3"

[task]
name = "flowforge/paper-814525462003843073"
description = "Grand Canonical Monte Carlo Simulation of CO₂ Adsorption in Hybrid Ultramicroporous Materials with Interpenetrated pcu Networks"

[agent]
timeout_sec = 50400

[verifier]
timeout_sec = 11400

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
