#!/usr/bin/env bash
set -euo pipefail

OUTDIR="/app/outputs"
mkdir -p "$OUTDIR"

# === solve preamble ===
#!/bin/bash
set -euo pipefail
python3 -m pip install -q --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple numpy
python3 /solution/generate_data.py

# === solve block: relative_energy_data.csv ===
echo "relative_energy_data.csv already generated by preamble"

# === solve block: angular_widths.csv ===
echo "angular_widths.csv already generated by preamble"

# === solve block: sticking_probability.csv ===
echo "sticking_probability.csv already generated by preamble"
