schema_version = "1.3"

[task]
name = "flowforge/paper-811971712089325569"
description = "Predict Density and Detonation Performance of SF5- and CF3-1,2,3-Triazoles"

[agent]
timeout_sec = 36000

[verifier]
timeout_sec = 11400

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
