schema_version = "1.3"

[task]
name = "flowforge/paper-813179938667495425"
description = "Parametrization and validation of a force field for alumina using DFT fitting"

[agent]
timeout_sec = 518400

[verifier]
timeout_sec = 11400

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
