schema_version = "1.3"

[task]
name = "flowforge/paper-814627781475303425"
description = "Reproducing Temperature-Dependent Thermodynamic Properties and Anharmonicity of Two-Dimensional Silicene and Germanene"

[agent]
timeout_sec = 172800

[verifier]
timeout_sec = 11400

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
