schema_version = "1.3"

[task]
name = "flowforge/paper-867752270672954072"
description = "Impair Pair Energetics and Band Gap in PbTe, SnTe, GeTe via DFT Supercell Method"

[agent]
timeout_sec = 43200

[verifier]
timeout_sec = 11400

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
