schema_version = "1.3"

[task]
name = "flowforge/paper-1203673158717014018"
description = "Prediction of Magnetic Superexchange Constants in Lithium Silver Fluorides"

[agent]
timeout_sec = 54000

[verifier]
timeout_sec = 18000

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
