schema_version = "1.3"

[task]
name = "flowforge/paper-811100250331676672"
description = "Calculation of Total and p_y-Orbital Density of States and Electronic Heat Capacity in Impure Chair-Like Graphane under Magnetic Field"

[agent]
timeout_sec = 18000

[verifier]
timeout_sec = 11400

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
