schema_version = "1.3"

[task]
name = "flowforge/paper-1025990641890361345"
description = "Compute magnetic moments, spin multiplicity, magnetic anisotropy energy, exchange coupling constant, and Curie temperature for UAu6 clusters and UAu4 monolayer and its hydrogenated derivative using DFT and Monte Carlo simulation."

[agent]
timeout_sec = 72000

[verifier]
timeout_sec = 11400

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
