schema_version = "1.3"

[task]
name = "flowforge/paper-977532169758965995"
description = "DFT+U simulations of charge-ordered metastable state in La0.25Sr0.75TiO3 bulk and thin films"

[agent]
timeout_sec = 72000

[verifier]
timeout_sec = 11400

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
