schema_version = "1.3"

[task]
name = "flowforge/paper-811951031733714945"
description = "HF/6-31G(d) Calculation of Molecular Dipole Moments in Gas and THF Solvent"

[agent]
timeout_sec = 18000

[verifier]
timeout_sec = 11400

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
