schema_version = "1.3"

[task]
name = "flowforge/paper-811828360945598464"
description = "Atomistic Simulation of Hydrogen Embrittlement in α‑Fe"

[agent]
timeout_sec = 43200

[verifier]
timeout_sec = 11400

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
