schema_version = "1.3"

[task]
name = "flowforge/paper-812744125639032833"
description = "DFT Formation Energy Calculation of Sb3Sn4"

[agent]
timeout_sec = 18000

[verifier]
timeout_sec = 11400

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
