schema_version = "1.3"

[task]
name = "flowforge/paper-811093079581786112"
description = "DFT Calculated C-H Activation Barriers of n-Hexane on Copper Step Edges"

[agent]
timeout_sec = 720000

[verifier]
timeout_sec = 11400

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
