schema_version = "1.3"

[task]
name = "flowforge/paper-811809864274673665"
description = "DFT calculation of mechanical and optical properties of delafossite CuAlO2"

[agent]
timeout_sec = 108000

[verifier]
timeout_sec = 11400

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
