schema_version = "1.3"

[task]
name = "flowforge/paper-812507272553955329"
description = "DFT calculation of hydrogen trapping in vacancy-oxygen complexes of Ti3AlC2"

[agent]
timeout_sec = 300000

[verifier]
timeout_sec = 11400

[environment]
docker_image = "dp-harbor-registry.cn-zhangjiakou.cr.aliyuncs.com/public/paper2arm-env:v1.0-20260708"
allow_internet = true
build_timeout_sec = 1800
